/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : MessageId,
  'content' : string,
  'role' : MessageRole,
  'timestamp' : Timestamp,
}
export interface ChatSession {
  'id' : ChatSessionId,
  'title' : string,
  'documentIds' : Array<DocumentId>,
  'messages' : Array<ChatMessage>,
  'owner' : UserId,
  'createdAt' : Timestamp,
}
export type ChatSessionId = bigint;
export interface ChatSessionInfo {
  'id' : ChatSessionId,
  'title' : string,
  'documentIds' : Array<DocumentId>,
  'createdAt' : Timestamp,
  'messageCount' : bigint,
}
export type DocumentId = bigint;
export interface DocumentInfo {
  'id' : DocumentId,
  'title' : string,
  'blob' : ExternalBlob,
  'fileSize' : bigint,
  'fileType' : string,
  'uploadedAt' : Timestamp,
}
export type ExternalBlob = Uint8Array;
export type MessageId = bigint;
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChatSession' : ActorMethod<
    [Array<DocumentId>, string],
    ChatSessionInfo
  >,
  'deleteChatSession' : ActorMethod<[ChatSessionId], undefined>,
  'deleteDocument' : ActorMethod<[DocumentId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatSession' : ActorMethod<[ChatSessionId], [] | [ChatSession]>,
  'getDocument' : ActorMethod<[DocumentId], [] | [DocumentInfo]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listChatSessions' : ActorMethod<[], Array<ChatSessionInfo>>,
  'listDocuments' : ActorMethod<[], Array<DocumentInfo>>,
  'renameDocument' : ActorMethod<[DocumentId, string], DocumentInfo>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[ChatSessionId, string], ChatMessage>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'uploadDocument' : ActorMethod<
    [string, string, bigint, ExternalBlob],
    DocumentInfo
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];