/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DocumentId = IDL.Nat;
export const ChatSessionId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ChatSessionInfo = IDL.Record({
  'id' : ChatSessionId,
  'title' : IDL.Text,
  'documentIds' : IDL.Vec(DocumentId),
  'createdAt' : Timestamp,
  'messageCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MessageId = IDL.Nat;
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'role' : MessageRole,
  'timestamp' : Timestamp,
});
export const UserId = IDL.Principal;
export const ChatSession = IDL.Record({
  'id' : ChatSessionId,
  'title' : IDL.Text,
  'documentIds' : IDL.Vec(DocumentId),
  'messages' : IDL.Vec(ChatMessage),
  'owner' : UserId,
  'createdAt' : Timestamp,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DocumentInfo = IDL.Record({
  'id' : DocumentId,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'fileSize' : IDL.Nat,
  'fileType' : IDL.Text,
  'uploadedAt' : Timestamp,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChatSession' : IDL.Func(
      [IDL.Vec(DocumentId), IDL.Text],
      [ChatSessionInfo],
      [],
    ),
  'deleteChatSession' : IDL.Func([ChatSessionId], [], []),
  'deleteDocument' : IDL.Func([DocumentId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatSession' : IDL.Func(
      [ChatSessionId],
      [IDL.Opt(ChatSession)],
      ['query'],
    ),
  'getDocument' : IDL.Func([DocumentId], [IDL.Opt(DocumentInfo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChatSessions' : IDL.Func([], [IDL.Vec(ChatSessionInfo)], ['query']),
  'listDocuments' : IDL.Func([], [IDL.Vec(DocumentInfo)], ['query']),
  'renameDocument' : IDL.Func([DocumentId, IDL.Text], [DocumentInfo], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([ChatSessionId, IDL.Text], [ChatMessage], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'uploadDocument' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [DocumentInfo],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DocumentId = IDL.Nat;
  const ChatSessionId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ChatSessionInfo = IDL.Record({
    'id' : ChatSessionId,
    'title' : IDL.Text,
    'documentIds' : IDL.Vec(DocumentId),
    'createdAt' : Timestamp,
    'messageCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MessageId = IDL.Nat;
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'role' : MessageRole,
    'timestamp' : Timestamp,
  });
  const UserId = IDL.Principal;
  const ChatSession = IDL.Record({
    'id' : ChatSessionId,
    'title' : IDL.Text,
    'documentIds' : IDL.Vec(DocumentId),
    'messages' : IDL.Vec(ChatMessage),
    'owner' : UserId,
    'createdAt' : Timestamp,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DocumentInfo = IDL.Record({
    'id' : DocumentId,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'fileSize' : IDL.Nat,
    'fileType' : IDL.Text,
    'uploadedAt' : Timestamp,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChatSession' : IDL.Func(
        [IDL.Vec(DocumentId), IDL.Text],
        [ChatSessionInfo],
        [],
      ),
    'deleteChatSession' : IDL.Func([ChatSessionId], [], []),
    'deleteDocument' : IDL.Func([DocumentId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatSession' : IDL.Func(
        [ChatSessionId],
        [IDL.Opt(ChatSession)],
        ['query'],
      ),
    'getDocument' : IDL.Func([DocumentId], [IDL.Opt(DocumentInfo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChatSessions' : IDL.Func([], [IDL.Vec(ChatSessionInfo)], ['query']),
    'listDocuments' : IDL.Func([], [IDL.Vec(DocumentInfo)], ['query']),
    'renameDocument' : IDL.Func([DocumentId, IDL.Text], [DocumentInfo], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([ChatSessionId, IDL.Text], [ChatMessage], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'uploadDocument' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [DocumentInfo],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };